matrix:
  include:
    - os: osx
      osx_image: xcode9.1
      sudo: required
    - os: linux
      sudo: required
      dist: trusty
      group: edge
      compiler: clang

language: c

branches:
  only:
    - master

cache:
  directories:
    - "./node_modules"
    - "${HOME}/.yarn-cache"

addons:
  apt:
    packages:
      - bsdtar
      - g++-multilib
      - gcc-multilib
      - graphicsmagick
      - icnsutils
      - rpm
      - xz-utils

before_install:
  - echo "🚦 Authorizing Build"
  - if [[ "${OSTYPE}" == "darwin"* ]] && [[ "${DEPLOY_MACOS}" == 0 ]]; then travis_terminate 0; fi
  - if [[ "${OSTYPE}" == "linux"* ]] && [[ "${DEPLOY_LINUX}" == 0 ]]; then travis_terminate 0; fi
  - echo "🔧 Setting up Node"
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/master/install.sh | NVM_DIR="${HOME}"/.nvm sh
  - source "${HOME}"/.nvm/nvm.sh && nvm install 8.5.0 && nvm use 8.5.0
  - npm --global update npm
  - npm --global install yarn
  - echo "🔧 Setting up RubyGems"
  - gem install package_cloud

install:
  - echo "📥 Installing Dependencies"
  - yarn install

script:
  - echo "📦 Building"
  - npm run build --metadata

after_success:
  - echo "📮 Deploying to Github"
  - npm run deploy
  - echo "📮 Deploying to PackageCloud"
  - cat .deblist | while read LINUX_DISTRIBUTION_SLUG; do package_cloud push "${TRAVIS_REPO_SLUG}/${LINUX_DISTRIBUTION_SLUG}" ./build/output/*.deb; done
  - cat .rpmlist | while read LINUX_DISTRIBUTION_SLUG; do package_cloud push "${TRAVIS_REPO_SLUG}/${LINUX_DISTRIBUTION_SLUG}" ./build/output/*.rpm; done

notifications:
  webhooks:
    on_failure: always
    on_start: never
    on_success: change
    urls:
      - https://webhooks.gitter.im/e/24d905038aa07dda37df
